# Generated by Django 4.2.20 on 2025-05-11 00:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название локации')),
                ('background_image', models.ImageField(blank=True, null=True, upload_to='locations/', verbose_name='Фоновое изображение')),
                ('question_count', models.PositiveSmallIntegerField(choices=[(1, '1 вопрос'), (2, '2 вопроса'), (3, '3 вопроса')], default=1, verbose_name='Число вопросов в локации')),
            ],
            options={
                'verbose_name': 'Локация',
                'verbose_name_plural': 'Локации',
            },
        ),
        migrations.CreateModel(
            name='TheoryQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(verbose_name='Текст теоретического вопроса')),
                ('answer1', models.CharField(blank=True, max_length=255, null=True, verbose_name='Вариант 1')),
                ('answer2', models.CharField(blank=True, max_length=255, null=True, verbose_name='Вариант 2')),
                ('answer3', models.CharField(blank=True, max_length=255, null=True, verbose_name='Вариант 3')),
                ('correct_answer', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3')], default=1, verbose_name='Правильный вариант')),
            ],
            options={
                'verbose_name': 'Теоретический вопрос',
                'verbose_name_plural': 'Теоретические вопросы',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст задачи')),
                ('additional_info', models.TextField(blank=True, null=True, verbose_name='Доп. информация')),
                ('difficulty', models.CharField(choices=[('easy', 'Лёгкий'), ('medium', 'Средний'), ('boss', 'Босс')], default='easy', max_length=10, verbose_name='Сложность')),
                ('is_for_boss', models.BooleanField(default=False, verbose_name='Для босса')),
                ('rank_points', models.PositiveIntegerField(verbose_name='Очки за прохождение')),
                ('hint', models.TextField(blank=True, null=True, verbose_name='Подсказка')),
                ('hint_cost', models.PositiveIntegerField(default=2, verbose_name='Стоимость подсказки')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='game.location', verbose_name='Локация')),
            ],
            options={
                'verbose_name': 'Задача',
                'verbose_name_plural': 'Задачи',
                'ordering': ['location', 'difficulty'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(help_text='Порядковый номер шага в цепочке', verbose_name='Порядок')),
                ('text', models.TextField(verbose_name='Текст вопроса')),
                ('question_type', models.CharField(choices=[('choice', 'Выбор варианта'), ('input', 'Свободный ввод')], default='choice', max_length=10, verbose_name='Тип вопроса')),
                ('correct_input', models.CharField(blank=True, help_text='Точное совпадение при вводе', max_length=255, null=True, verbose_name='Правильный ответ (для ввода)')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='game.task', verbose_name='Задача')),
            ],
            options={
                'verbose_name': 'Вопрос',
                'verbose_name_plural': 'Вопросы',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ChoiceOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255, verbose_name='Текст варианта')),
                ('is_correct', models.BooleanField(default=False, verbose_name='Правильный вариант')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='game.question', verbose_name='Вопрос')),
            ],
            options={
                'verbose_name': 'Вариант ответа',
                'verbose_name_plural': 'Варианты ответов',
            },
        ),
    ]
